services:
  policy-chatbot:
    build: .
    container_name: company-policy-chatbot
    image: policy-chatbot
    ports:
      - "8000:8000"
    volumes:
      - vector_data:/app/vector_store
    environment:
      - HF_TOKEN=${HF_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  vector_data:
    
